# Generated by Django 5.2.9 on 2025-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='adddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
