# Generated by Django 5.2.9 on 2025-12-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_adddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='adddress',
            new_name='address',
        ),
    ]
